# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Blueprints | MUS/DCS 256      
email: lgoldford@bates.edu    
description: >- # this means to ignore newlines until "baseurl:"
  Winter/Spring 2026 | Mondays, Wednesdays, and Fridays from 13:10—14:30 | Bates Sound Studio (Olin 302)    
twitter_username: einbahnstrasse  
github_username: einbahnstrasse  
minimal_mistakes_skin: sunrise   
search: true
logo: "/assets/CSS.favicon.v01c.drawio.svg"
lunr:  
  search_within_pages: true   

baseurl: /MUS256-Blueprints-WS2026

# Build settings
markdown: kramdown
remote_theme: mmistakes/minimal-mistakes
# Outputting
permalink: /:categories/:title/
paginate: 5 # amount of posts to show
paginate_path: /page:num/
timezone: # https://en.wikipedia.org/wiki/List_of_tz_database_time_zones

include:
  - _pages

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/

# Plugins (previously gems:)
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jemoji
  - jekyll-include-cache
  # - jekyll-toc  

author:
  name   : "Louis Goldford"
  avatar : "/assets/images/Goldford.square.sm.jpg"
  bio    : "composer"
  links:
    - label: "Portfolio"
      icon: "fas fa-fw fa-link"
      url: "https://louisgoldford.com/"
    - label: "Twitter"
      icon: "fab fa-fw fa-twitter-square"
      url: "https://twitter.com/einbahnstrasse"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/einbahnstrasse"
    - label: "Instagram"
      icon: "fab fa-fw fa-instagram"
      url: "https://instagram.com/louis.goldford"

footer:
  links:
    - label: "Twitter"
      icon: "fab fa-fw fa-twitter-square"
      url: "https://twitter.com/einbahnstrasse"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/einbahnstrasse"
    - label: "Instagram"
      icon: "fab fa-fw fa-instagram"
      url: "https://instagram.com/louis.goldford"

defaults:
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
      read_time: true
      # words_per_minute: 200
      comments: true
      share: true
      related: true
  # _pages
  - scope:
      path: "_pages"
      type: pages
    values:
      layout: single
      author_profile: true

category_archive:
  type: liquid
  path: /categories/
tag_archive:
  type: liquid
  path: /tags/

# Markdown Processing
kramdown:
  input: GFM
  hard_wrap: false
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  # toc_levels: 1..6
  toc_levels: 2..6
  smart_quotes: lsquo,rsquo,ldquo,rdquo
  enable_coderay: false

# Schedule-specific variables   

weekly-deadline-statement: Unless otherwise noted, assignments are always due online on GitHub at 11:59 PM the following Monday night each week!
Bates-calendar: https://calendar.google.com/calendar/embed?src=bates.edu_hq580lfthp57u4bolk05oskgbs%40group.calendar.google.com&ctz=America%2FNew_York 

week-01: Jan 14      
week-02: Jan 19      
week-03: Jan 26      
week-04: Feb 2      
week-05: Feb 9      
# February Recess: Feb 16–20 (no classes)
week-06: Feb 23      
week-07: Mar 2      
week-08: Mar 9      
# March Recess: Mar 18–22 (no classes)      
week-09: Mar 23      
week-10: Mar 30      
week-11: Apr 6      
week-12: Apr 13      
# week-13: N/A
# week-14: N/A
# week-15: N/A

week-01-topic: Course Overview 
week-02-topic: Signal Flow in MaxMSP
week-03-topic: Filters + Resonance
week-04-topic: Formant Modeling + Source–Filter Systems
week-05-topic: Karplus–Strong + Waveguide String Models
week-06-topic: Bowed and Wind Instrument Physical Models
week-07-topic: Modalys — Strings, and Plates
week-08-topic: Material Properties and Hybrid Physical Models
week-09-topic: SPAT~ and Multichannel Audio
week-10-topic: Computer-Assisted Composition  
week-11-topic: Finite Elements, Meshes, and Modal Analysis
week-12-topic: Real-Time Analysis/Resynthesis  
week-13-topic: Final Integration & Project Presentations
     
# week-14-topic: Final Concert + Exam            
# week-15-topic: Finals Week            
# week-16-topic: Modular Synthesis (Part 2) in VCV Rack      
# week-17-topic: Modular Synthesis (Part 3) in VCV Rack     
# week-18-topic: Listening Session (Final Projects)     

# language plugin settings   

languages: ["en", "sv", "de", "fr"]  
default_lang: "en"  
exclude_from_localization: ["javascript", "images", "css", "public"]  
parallel_localization: true  
